---
- hosts: mysql
  become: true
  
  vars_prompt:  
    - name: "sname"
      prompt: "What is the username to add?"
      private: no
    - name: "sfull"
      prompt: "What is the full name?"
      private: no  
  
  roles:
    - usercreation
